services:
  mercadolibre:
    image: postgres:15
    container_name: mercadolivre
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vendas
    ports:
      - "5430:5430"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
